# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [3]:
import numpy as np
my_list=[1,2,3]
my_list



[1, 2, 3]

In [5]:
#to convert kist into array we used np.array 
np.array(my_list)

array([1, 2, 3])

In [4]:
matrix=[(1,2,3),(4,5,6),(4,8,9)]
matrix

[(1, 2, 3), (4, 5, 6), (4, 8, 9)]

In [9]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [10]:
np.arange(0,10)
#not included end value that is 10 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(0,12,2)
#skipp by 2 and not included 12


array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5),dtype=int)
#we can change the datatype by adding a dtype attribute 
#'int32'or int or 'int64'


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
np.ones(3)

array([1., 1., 1.])

In [18]:
type(np.ones(2))

numpy.ndarray

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [22]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [22]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [27]:
np.eye(4)
#values are in float 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [27]:
np.random.rand()
#1 is not included 

array([0.41955476, 0.20981469])

In [29]:
np.random.rand(5,5)
#it is uniform distributed

array([[0.82216187, 0.88618224, 0.89915269, 0.83845778, 0.64482998],
       [0.55087404, 0.40041918, 0.02957256, 0.34151653, 0.94145383],
       [0.28804761, 0.84196266, 0.26219399, 0.82553302, 0.77885018],
       [0.88667251, 0.67906405, 0.50730122, 0.55431246, 0.67974593],
       [0.36455539, 0.79389264, 0.42052825, 0.14956505, 0.43110813]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [31]:
np.random.randn(2)
#random number is generated form 3 to -3

array([-1.70047823,  0.12927241])

In [32]:
np.random.randn(5,5)

array([[ 1.74295737,  1.04549489, -0.11123568,  0.44199588, -0.39462392],
       [-0.58725025,  0.08158263, -0.693102  , -1.58009542, -0.5457031 ],
       [-1.57204893, -0.61579815,  1.46876084,  1.70848876,  0.3989502 ],
       [-2.50208967,  0.07212377,  0.17170408, -0.36428233,  1.07091453],
       [-1.36682804, -0.54816673,  0.32247078,  0.52556651,  1.10629606]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [8]:
np.random.randint()

0

In [39]:
np.random.randint(1,100,10)
#100 will be not included

array([41, 67, 95, 35, 23,  6, 42, 44, 77, 95])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [30]:
arr=np.arange(25)

In [31]:
rearr=np.random.randint(0,50,10)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
rearr

array([ 5,  1, 41, 17, 22, 46, 27,  0,  9, 38])

## Reshape
Returns an array containing the same data with a new shape.

In [34]:
t=arr.reshape(5,5)
t.shape

(5, 5)

##### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [52]:
rearr.max()

46

In [53]:
rearr.argmax()
#index of the max element

5

In [54]:
rearr.min()

0

In [55]:
rearr.argmin()

7

## Shape

Shape is an attribute that arrays have (not a method):

In [58]:
# Vector
arr.shape

(25,)

In [60]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [61]:
arr.reshape(1,25).shape

(1, 25)

In [62]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [65]:
arr.reshape(25,1).shape
#25 rows and 1 column 

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [66]:
arr.dtype

dtype('int32')






# Great Job!